# Generated by Django 4.2.23 on 2025-08-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="price_authority",
            field=models.CharField(default="mcx", max_length=32),
        ),
        migrations.AddField(
            model_name="transaction",
            name="price_currency",
            field=models.CharField(default="INR", max_length=8),
        ),
        migrations.AddField(
            model_name="transaction",
            name="price_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="price_unit",
            field=models.CharField(default="g", max_length=8),
        ),
    ]
